export const actionTypes = {
  FETCH_TITLE: "FETCH_TITLE",
  FETCH_NATIONALITY: "FETCH_NATIONALITY",
  FETCH_GENDER: "FETCH_GENDER",
  FETCH_PHONECODE: "FETCH_PHONECODE",
  FETCH_MEMBER: "FETCH_MEMBER",
  POST_INFORMATION_SUCESS: "POST_INFORMATION_SUCESS",
  POST_INFORMATION_FAIL: "POST_INFORMATION_FAIL",
  FETCH_LIST: "FETCH_LIST",
  DELETE_SINGLE_LIST: "DELETE_SINGLE_LIST",
  DELETE_ALL_LIST: "DELETE_ALL_LIST",
  CHANGE_SINGLE_CHECKED: "CHANGE_SINGLE_CHECKED",
  CHANGE_ALL_CHECKED: "CHANGE_ALL_CHECKED"
};
